---
evaluation_metrics:         # The metrics which will be calculated for every epoch
  - loss                    # Can be omitted as loss is a compulsory metric
  - accuracy*               # Asterisk indicates to set as criterion metric for selecting best epoch
activation:                 # Activation function
  choice: ReLU              # Same name as function in in torch.nn
  kwargs: {}                # Parameters for activation function call. {} to indicate PyTorch defaults
optimization:               # Optimization function
  choice: SGD               # Same name as function in torch.optim
  kwargs:                   # Parameters for activation function call
    lr: 0.001
    momentum: 0.9
loss:                       # Loss function
  choice: CrossEntropyLoss  # Same name as function in in torch.nn
  kwargs: {}                # Parameters for activation function call. {} to indicate PyTorch defaults
regularization:             # Regularization terms (currently only supports L2)
  L2: 0.001                 # Lagrange multiplier (i.e. lambda) value
batch_size: 4               # Mini-batch size for dataloaders
num_epochs: 5               # Number of training epochs
checkpoints:                # Checkpoint related configuration [OPTIONAL]
  dir:                      # Directory under which checkpoints are saved [DEFAULT]. None indicates experiment directory
  identifier: pth           # Identifier name of each checkpoint [DEFAULT]
  best_prefix: best         # Prefix of the best checkpoint [DEFAULT]. E.g. best.pth.tar
  last_prefix: last         # Prefix of the last checkpoint [DEFAULT]. E.g. last.pth.tar
  extension: tar            # File extension for checkpoint files [DEFAULT]
  stats_filename: stats.yml # Filename for reviewing best and last checkpoint statistics [DEFAULT]. It will be saved in the same directory as checkpoints
logs:                       # Logging related configuration [OPTIONAL]
  logger: log.log           # Filename which logger will log to [DEFAULT]. It sits in the same directory as the experiment
  tensorboard: TB_logdir    # The logdir for Tensorboard [DEFAULT]. It sits in the same directory as the experiment
remarks: This is a great experiment!
