---
evaluation_metrics:
  - loss*
  - accuracy
network:
  activation:
    choice: LeakyReLU
    kwargs:
      negative_slope: 0.01
optimization:
  choice: Adam
  kwargs:
    lr: 0.001
loss:
  choice: CrossEntropyLoss
transforms:
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
regularization:
  L2: 0.001
batch_size: 128
num_epochs: 5
wandb:
  init:
    project: jinlib
  watch:
    log: all
    log_freq: 10
remarks: Alternative choice of activation, optimization and hyperparameters
