---
evaluation_metrics:
  - loss*
  - accuracy
activation:
  choice: LeakyReLU
  kwargs:
    negative_slope: 0.01
optimization:
  choice: Adam
  kwargs:
    lr: 0.001
loss:
  choice: CrossEntropyLoss
  kwargs: {}
regularization:
  L2: 0.001
batch_size: 128
num_epochs: 5
remarks: Alternative choice off activation, optimization and hyperparameters
