---
evaluation_metrics:
  - loss*
  - accuracy
activation:
  choice: LeakyReLU
  kwargs:
    negative_slope: 0.01
optimization:
  choice: Adam
  kwargs:
    lr: 0.001
loss:
  choice: CrossEntropyLoss
  kwargs: {}
regularization:
  L2: 0.001
batch_size: 128
num_epochs: 5
wandb:
  init:
    project: jinlib-example-2
  watch:
    log: all
    log_freq: 10
remarks: Alternative choice of activation, optimization and hyperparameters
