---
evaluation_metrics:
  - loss        # can be omitted as loss is a compulsory metric
  - accuracy*   # asterisk indicates to select as criterion metric for selecting best epoch
network:
  activation:
    choice: ReLU
optimization:
  choice: SGD
  kwargs:
    lr: 0.001
    momentum: 0.9
loss:
  choice: CrossEntropyLoss
transforms:
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
batch_size: 4
num_epochs: 5
wandb:
  init:
    project: jinlib
    id: experiment_1
    resume: 'allow'
  watch:
    log: all
    log_freq: 10
remarks: This experiment setting follows that of https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html
