---
evaluation_metrics:
  - loss        # can be omitted as loss is a compulsory metric
  - accuracy*   # asterisk indicates to select as criterion metric for selecting best epoch
activation:
  choice: ReLU
  kwargs: {}
optimization:
  choice: SGD
  kwargs:
    lr: 0.001
    momentum: 0.9
loss:
  choice: CrossEntropyLoss
  kwargs: {}
batch_size: 4
num_epochs: 10
checkpoints:
  dir: 
  basename: ckpt
  best_suffix: best
  last_suffix: last
  extension: pth
  stats_filename: stats.yml
logs:
  logger: log.log
  tensorboard: TB_logdir
remarks: This experiment setting follows that of https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html
